rcbops/pytest-rpc

- .travis.yml
- LICENSE
- MANIFEST.in
- README.rst
- pytest_rpc.py
- requirements.txt
- setup.py
- tests/conftest.py
- tests/test_rpc.py
- tox.ini
Created a py.test plug-in using the following documentation:
https://github.com/pytest-dev/cookiecutter-pytest-plugin
> (ASC-162) Create py.test Plug-in Using Cookiecutter

- pytest_rpc.py
- requirements.txt
- tests/test_rpc.py
@ryan-rs  I think I am going to need some advise on dealing with the `DomNode` class.  I have the information I want in the properties but I am having a hard time getting the info out.
> ASC-308 capture start and end times for test cases

- data/molecule_junit.xsd
- pytest_rpc.py
- requirements.txt
- setup.py
- tests/test_rpc.py
Add a "molecule_junit.xsd" file and test to validate that plug-in is producing
a valid JUnitXML file for Molecule tests.
> ASC-367 Implement XSD Schema Checking

- Makefile
- requirements.txt
Added a Makefile that provides tasks for assisting developers with their
workflow.
> ASC-354 Add Makefile

- CONTRIBUTING.rst
- README.rst
Updated the docs to reorganize and reflect the addition of a Makefile.
> ASC-356 Update Documentation

- Makefile
- tox.ini
The linter configuration for tox and the make file was incorrect.
Fixed!
Blocked by #9 and #10.
> ASC-382 Fix Linting Issues

- Makefile
- bump before you build a new version
> MAINT fix release task order

- tests/helpers/test_openstack_name_list.py
This commit adds unit test for `openstack_name_list` helper.
> ASC-705 Add unit test for openstack_name_list

- tests/helpers/test_delete_volume.py
This commit adds unit tests for the `delete_volume` helper.
> ASC-705 Add unit tests for delete_volume

- pytest_rpc/helpers.py
- tests/helpers/test_generate_random_string.py
This commit adds unit tests for the `generate_random_string` helper.
> ASC-705 Add unit tests for generate_random_string

- tests/helpers/test_asset_is_in_the_list.py
- tests/helpers/test_asset_not_in_the_list.py
This PR adds unit tests for the `asset_is_in_the_list` and `asset_not_in_the_list` helpers.
> ASC-705 Add unit tests for asset_*_in_the_list

- requirements.txt
- tests/helpers/test_ping_ip_from_utility_container.py
This commit adds unit tests for the `ping_ip_from_utility_container`
helper.
> ASC-705 Unit tests ping_ip_from_utility_container

- tests/helpers/test_get_id_by_name.py
This commit adds unit tests for the `get_id_by_name` helper.
> ASC-705 Add unit tests for get_id_by_name

- pytest_rpc/helpers.py
- requirements.txt
- tests/helpers/test_create_bootable_volume.py
This commit adds unit tests for `create_bootable_volume` helper.
> ASC-705 Add unit tests for create_bootable_volume

- requirements.txt
- tests/helpers/test_stop_server_instance.py
This commit adds unit tests for the `stop_server_instance` helper.
> ASC-705 Add unit tests for stop_server_instance

- pytest_rpc/helpers.py
- tests/helpers/test_parse_swift_recon.py
- tests/helpers/test_parse_swift_ring_builder.py
- tests/helpers/test_run_on_container.py
- tests/helpers/test_run_on_swift.py
This commit adds helper methods used in the support of swift validation
tests.
> ASC-744 Add swift helpers

- pytest_rpc/__init__.py
- collects the MOLECULE_GIT_COMMIT ENV so ZigZag can build links
> MAINT add collection of MOLECULE_GIT_COMMIT

- tests/helpers/test_delete_instance.py
- tests/helpers/test_delete_volume.py
- tests/helpers/test_get_expected_value.py
- tests/helpers/test_resource_in_list.py
Some minor fixes for pep8 warnings and misc. changes to improve readability.
> MAINT - Fix Formatting in Helper Tests

- pytest_rpc/helpers.py
- tests/helpers/test_get_expected_value.py
Update the "get_expected_value" helper to allow for case insensitive matching.
> ASC-1048 Case Insensitive Matching

- tests/helpers/test_ping_from_mnaio.py
Add unit test coverage for 'ping_from_mnaio' helper.
> ASC-1547 Add Unit Test Coverage

- tests/helpers/test_expect_os_property.py
- tests/helpers/test_ping_from_mnaio.py
Add unit test coverage for the 'expect_os_property' helper.
>  ASC-1546 Add Unit Test Coverage
